feat: add optional dep-kind parameter
coreos/cargo-vendor-filterer pull request #102
Opened 2024-10-14 15:43 UTC by piotr-sk

Adds an optional `--dep-kinds` flag allowing to filtering out dev or build dependencies similarly to the edges option in cargo tree (<https://doc.rust-lang.org/cargo/commands/cargo-tree.html>)

Possible values are:

- `all` (default)
- `normal`
- `build`
- `dev`
- `no-normal`
- `no-build`
- `no-dev`

The goal was to modify as little as possible the existing code base and to add the additional filtering only if the optional parameter is set.
Ideally this filter will be added to the cargo metadata, so that the commit can be reworked to apply the filter directly in function `add_packages_for_platform()`

Closes #101

2024-10-14 15:56 UTC, piotr-sk commented
@cgwalters it turned out to be more complicated that I initially thought, but here is a solution with hopefully minimal impact to everyone not needing the additional filtering.

Let me know what you think.

2024-10-17 19:40 UTC, piotr-sk commented
OK provided we can agree on a reasonable timeline for your next cycle :wink:

The change is fully backwards compatible and nothing additional is computed or filtered until the `dep-kinds` flag is set via command line or toml file.

Some background to the last commit: the only dev dependency of this crate `once_cell` becomes a normal dependency after release 0.5.15 because the update of tempfile to v3.13.0 pulls it in. See the cargo tree output after the update:

```console
$ cargo tree --package once_cell --invert
once_cell v1.20.2
├── openssl v0.10.68
│   └── cargo-vendor-filterer v0.5.14
├── serial_test v3.1.1
│   [dev-dependencies]
│   └── cargo-vendor-filterer v0.5.14
└── tempfile v3.13.0
    └── cargo-vendor-filterer v0.5.14
[dev-dependencies]
└── cargo-vendor-filterer v0.5.14
```

To ensure the logic is tested I pull in a `serial_test` dev dependency and use it marking some tests for parallel execution (i.e. no slow-down to testing).

Should bringing this dev-dependency for testing purposes be a problem, I can remove problematic tests or use a different crate.

2024-10-17 23:46 UTC, cgwalters commented
The serial_test seems fine to me, skimming https://crates.io/crates/serial_test/reverse_dependencies it's pulled in by rustix e.g.

Still without looking deep at the code yet...it looks like the tracking issue you filed against cargo got put in their (looong) backlog, which is totally understandable.

The bar is relatively lower for landing features here :smile: (which is both good and bad). My biggest concern is:

- `cargo tree` certainly looks like it was mainly created for human consumption...yes, with `--quiet` at least the Unicode line drawing characters are omitted...but still, I'd be a bit happier if it had a `--json` that was supported with `cargo_metadata` equivalent.

Subconcerns:

- Relatively minor bikeshed: What if `cargo vendor` decides to accept `--dep-kinds` but wants to change some of the possible values? So far there's only a bit of precedent in this project for *CLI* options accepted only by this tool but not `cargo vendor`. I wonder if we should make it something a bit more "namespaced" like `--filter-dep-kinds` or something and save the `--dep-kinds` for `cargo vendor` (and if it gets accepted there we make it an alias?)
- This is effectively a new algorithm for computing dependencies that only shares high level logic with the `cargo metadata` path...I can't think of a concrete problem but I'd be a bit more comfortable if we e.g. *always* used `cargo tree` perhaps so there was only one dependency-parsing path? (Yes, more invasive...maybe in CI we could assert that the two paths compute the same results?)

2024-10-17 23:49 UTC, cgwalters commented on src/dep_kinds.rs
> +            if tokens.len() < 2 {
I like using destructuring matches for things like this, e.g.:

```
let [package, version] = tokens.as_slice() else {
  anyhow::bail!("Invalid output received from cargo tree: {line}");
};
```

2024-10-17 23:49 UTC, cgwalters commented on src/dep_kinds.rs
> +            let version = &tokens[1][1..tokens[1].len()];
The "need to remove the initial v" comment should be here right? How about:
```
let version = tokens[1].strip_prefix("v").ok_or_else(|| anyhow!("Invalid version: {version});
```

2024-10-19 17:53 UTC, piotr-sk commented on src/dep_kinds.rs
> +            if tokens.len() < 2 {
In principle, it is an excellent idea.

In practice, cargo tree generates extra tokens for repeated crates (example: `serde v1.0.210 (*)`), local crates (path to file), etc. 
Thus, each line can contain more than two elements, and this should not trigger an error.

2024-10-19 18:19 UTC, piotr-sk commented
Thanks for the review.

I agree with your main point that `cargo tree` is intended for people and not machines.

Initially, I started by changing the `add_packages_for_platform()` to use `cargo tree` instead of `cargo metadata`, but I do not think it would be a good solution in the long run for the reasons you've mentioned above.
Moreover, when cargo evolves and <https://github.com/rust-lang/cargo/issues/10718> gets implemented, we should be able to use `cargo metadata` only.
To prepare for this, I propose to keep the usage of `cargo tree` in a separate module and only for people who explicitly set this parameter to anything else than the default, so it can be more easily removed afterwards.

I like your idea of avoiding a potential conflict with the `cargo metadata` CLI parameter name.
When I was updating the documentation, the name of `--keep-dep-kinds` seemed a more straightforward solution.
What do you think?

2024-10-19 18:21 UTC, cgwalters commented on src/dep_kinds.rs
> +            if tokens.len() < 2 {
> Thus, each line can contain more than two elements, and this should not trigger an error.

That's just

```
let [package, version, ..] = tokens.as_slice() else {
  anyhow::bail!("Invalid output received from cargo tree: {line}");
};
```

right?

2024-10-19 18:31 UTC, piotr-sk commented on src/dep_kinds.rs
> +            if tokens.len() < 2 {
Thanks, I've learned a new Rust trick today :+1:

2024-10-19 19:05 UTC, cgwalters requested changes
Just one doc change that needs doing and a nit, otherwise looks good to me

2024-10-19 19:05 UTC, cgwalters commented on README.md
> +keep_dep_kinds = "no-dev"
Isn't it `keep-dep-kinds` since we're using `kebab-case`?

2024-10-19 19:05 UTC, cgwalters commented on README.md
> +- `keep_dep_kinds`: Specify which dependencies kinds to keep.
Ditto

2024-10-19 19:05 UTC, cgwalters commented on src/dep_kinds_filtering.rs
> +    manifest_paths: &Vec<Option<&Utf8Path>>,
Very minor nit but generally slices are preferred over `&Vec`, i.e.
```suggestion
    manifest_paths: &[Option<&Utf8Path>],
```

2024-10-19 19:12 UTC, cgwalters commented
Ah yeah now we need to drop the unnecessary `vec![]` which can just be `[]`

2024-10-19 19:12 UTC, piotr-sk commented on README.md
> +keep_dep_kinds = "no-dev"
Sure, well spotted.

2024-10-19 19:19 UTC, cgwalters commented
> To prepare for this, I propose to keep the usage of cargo tree in a separate module and only for people who explicitly set this parameter to anything else than the default, so it can be more easily removed afterwards.

SGTM.

> When I was updating the documentation, the name of --keep-dep-kinds seemed a more straightforward solution.
What do you think?

This is also fine by me. It seems somewhat unlikely that cargo would add the option with the same name but different functionality in the end too.

2024-10-19 19:20 UTC, cgwalters approved these changes

2024-10-19 19:22 UTC, merged

2024-10-19 19:25 UTC, cgwalters commented
Thanks for your contribution!

OK now I think we should get https://github.com/coreos/cargo-vendor-filterer/pull/107 in after the submitter comes back with fixes and then I think we can do a new release later this next week.

It's probably about time to submit that next release to various Rust news channels like reddit.com/r/rust perhaps? Probably everyone who needs this project has already found it but still it's important to talk about what we're doing sometimes.

2024-10-19 20:00 UTC, piotr-sk commented
Thanks for your detailed review and I agree with the proposed next steps.  

I think it makes sense to mention this project in relevant open cargo issues – this is how we found your project as a solution to a not-yet-solved point there.