improvement: add option `--no-default-features` and `--features`
coreos/cargo-vendor-filterer pull request #92
Opened 2024-03-31 05:51 UTC by uncomfyhalomacro

This is still not tested if it works.

## Changes not documented
 - Used flag description from `cargo build`:
 ```
      -F, --features <FEATURES>  Space or comma separated list of features to activate
      --all-features             Activate all available features
      --no-default-features      Do not activate the `default` feature
 ```

**Reference issues/prs**: #91

2024-03-31 15:33 UTC, cgwalters requested changes
Thanks for working on this!  Just some nits.

As far as a test case, the Rust tests in this project only test vendoring our own code, which doesn't have any features.  However, if you look at the Github action flow, we test vendoring nushell, protobuf and netavark and at least nushell definitely has features.

Looks like in the current code `wasi` is optional so we could test with adding that as a feature?

2024-03-31 15:33 UTC, cgwalters commented on src/main.rs
> +    no_default_features: Option<bool>,
I think just `bool` here is fine, the default is false.

2024-03-31 15:33 UTC, cgwalters commented on src/main.rs
> +    /// Space or comma separated list of features to activate
Let's copy the cargo help and say "This flag may be specified multiple times, which enables all specified features."

2024-03-31 15:33 UTC, cgwalters commented on src/main.rs
> +    no_default_features: Option<bool>,
Also can just be `bool`.

2024-03-31 15:33 UTC, cgwalters commented on src/main.rs
> +    features: Option<Vec<String>>,
This one can just be `Vec<String>` too, right?  See below

2024-03-31 15:33 UTC, cgwalters commented on src/main.rs
> +            if !some_features.is_empty() {
Here we handle both the "option unset" and "empty vec" case, but if we changed to drop the option this code can just test "some_features.is_empty()".

2024-03-31 21:38 UTC, cgwalters commented on src/main.rs
> +            && !args.no_default_features
I guess in retrospect, we're inconsistent now with the `Option<bool>` for `all_features`...I don't remember why I did that now.  The logic here is checking for "was the argument provided", but there's no way to do e.g. `cargo vendor --all-features=false` - you can only provide a single bit, so there's no distinguishing between "option unset" and "option set to false".

So we can do a followup cleanup to drop that `Option` too I think.

2024-03-31 21:40 UTC, cgwalters approved these changes
Thanks!

2024-03-31 21:43 UTC, cgwalters commented
Oh hmm, unit tests aren't happy

> called `Result::unwrap()` on an `Err` value: Error("missing field `no-default-features`", line: 0, column: 0)

Ah I bet we need a `#[serde(default)]` for the new value in `struct VendorFilter`.  Which I guess is an argument to just be consistent and use `Option<bool>` there too for now (I don't have a strong opinion).  I think not having the `Option` in the clap bits is right at least though.

2024-03-31 23:48 UTC, uncomfyhalomacro commented
> Oh hmm, unit tests aren't happy
> 
> > called `Result::unwrap()` on an `Err` value: Error("missing field `no-default-features`", line: 0, column: 0)
> 
> Ah I bet we need a `#[serde(default)]` for the new value in `struct VendorFilter`. Which I guess is an argument to just be consistent and use `Option<bool>` there too for now (I don't have a strong opinion). I think not having the `Option` in the clap bits is right at least though.

yeah let's just revert back to using the `Option` for now.

2024-04-01 00:26 UTC, uncomfyhalomacro commented
I will attempt doing a cleanup with all features too. just a small quick change.

2024-04-01 11:55 UTC, cgwalters approved these changes
Thanks!

2024-04-01 11:55 UTC, cgwalters commented on .github/workflows/ci.yml
> -          rm -rfv true
Heh wow yes, that was a confusing thing before...

2024-04-01 12:25 UTC, merged

2024-04-01 12:26 UTC, cgwalters commented
(Note to all of us, I had to update the branch protection rules for the nushell version, I think we can simplify this in the future by dropping the version from the job name)

2024-04-01 13:38 UTC, cgwalters commented
@uncomfyhalomacro can you review https://github.com/coreos/cargo-vendor-filterer/pull/93 ?